# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(default=b'unknown', max_length=100, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('magnet_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('display_title', models.CharField(max_length=100, unique=True)),
                ('imdb_url', models.TextField()),
                ('imdb_img_url', models.TextField()),
                ('current_season', models.PositiveIntegerField()),
                ('last_seen_episode', models.PositiveIntegerField()),
                ('is_next_episode_available', models.BooleanField()),
                ('next_episode_date', models.DateField(default=None, null=True)),
                ('update_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='tvshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvshows', to='Series.TVShow'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='Series.Season'),
        ),
    ]
