# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='tvshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='Series.TVShow'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='imdb_img_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='imdb_url',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
