# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0002_auto_20170401_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='url',
        ),
    ]
