# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0003_remove_tvshow_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='imdb_url',
            new_name='info_url',
        ),
        migrations.RenameField(
            model_name='tvshow',
            old_name='imdb_img_url',
            new_name='poster_url',
        ),
    ]
