# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0004_auto_20170402_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='display_title',
        ),
    ]
