# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0005_remove_tvshow_display_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='current_season',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='last_seen_episode',
        ),
        migrations.AddField(
            model_name='season',
            name='info_url',
            field=models.CharField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='magnet_link',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
