# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0009_auto_20170422_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='airdate',
            field=models.DateField(default=None, null=True),
        ),
    ]
