# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0010_episode_airdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='last_watched',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 12, 24, 39, 433000, tzinfo=utc)),
        ),
    ]
