# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0011_tvshow_last_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='last_watched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
