# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0012_auto_20170405_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='active',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='active_season',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
