# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0014_auto_20170405_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='next_episode_date',
        ),
    ]
