# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Series', '0015_remove_tvshow_next_episode_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=b'', max_length=1000)),
                ('file_name', models.CharField(default=b'', max_length=100)),
                ('file_size', models.CharField(default=b'unknown', max_length=100)),
                ('seeds_number', models.PositiveIntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magnets', to='Series.Episode')),
            ],
        ),
    ]
